# Generated by Django 3.0.5 on 2020-04-28 17:54

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20200427_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
