# Generated by Django 3.0.5 on 2020-04-28 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='contact',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='about_us',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='references',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtp_email',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtp_port',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtp_server',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
