# Generated by Django 3.0.5 on 2020-04-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20200430_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='icon',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
